name: CI Advanced (MLflow + Docker)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  advanced:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. Install dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow pandas scikit-learn

      # 4. Run MLflow Project (Training)
      - name: Run MLflow Project
        run: |
          mlflow run MLProject --env-manager=local

      # 5. Get latest MLflow run ID
      - name: Get latest MLflow run ID
        run: |
          echo "RUN_ID=$(ls -td mlruns/*/* | head -1 | awk -F'/' '{print $(NF-1)}')" >> $GITHUB_ENV

      # 6. Upload MLflow artifacts to GitHub Repository
      - name: Upload MLflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: mlruns/

      # 7. Login to Docker Hub
      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
            -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 8. Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t logreg-mlflow MLProject

      # 9. Tag Docker Image
      - name: Tag Docker Image
        run: |
          docker tag logreg-mlflow \
            ${{ secrets.DOCKER_USERNAME }}/logreg-mlflow:latest

      # 10. Push Docker Image
      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/logreg-mlflow:latest
